kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: dependencies
    image: r-base
    commands:
      - make dependency
      - R -e "install.packages('packrat')"
      - R -e "packrat::restore()"
  
  - name: build
    image: r-base
    commands:
      - make
  
  - name: install
    image: r-base
    commands:
      - make install
  
  - name: check
    image: r-base
    commands:
      - make check
