A = sample(c("a", "b"), 5000, replace = TRUE, prob = c(0.1, 0.9))
B = sample(c("a", "b", "c"), 5000, replace = TRUE, prob = c(0.4, 0.2, 0.4))
C = sample(c("a", "b", "c", "d"), 5000, replace = TRUE, prob = c(0.25, 0.25, 0.4, 0.1))
H = rnorm(5000, mean = 2.34, sd = 0.12)
D = numeric(5000)
D[A == "a"] = 5 + H[A == "a"] + rnorm(length(which(A == "a")), sd = 0.5)
D[A == "b"] = 10 + H[A == "b"] + rnorm(length(which(A == "b")), sd = 0.3)
E = numeric(5000)
E[B == "a"] = 1 + 2.35 * D[B == "a"] + rnorm(length(which(B == "a")), sd = 0.5)
E[B == "b"] = 4 + 1.18 * D[B == "b"] + rnorm(length(which(B == "b")), sd = 1)
E[B == "c"] = 8 + 0.67 * D[B == "c"] + rnorm(length(which(B == "c")), sd = 1.5)
F = character(5000)
F[(B == "a") & (C == "a")] = sample(c("a", "b"), length(which((B == "a") & (C == "a"))), replace = TRUE, prob = c(0.1, 0.9))
F[(B == "a") & (C == "b")] = sample(c("a", "b"), length(which((B == "a") & (C == "b"))), replace = TRUE, prob = c(0.5, 0.5))
F[(B == "a") & (C == "c")] = sample(c("a", "b"), length(which((B == "a") & (C == "c"))), replace = TRUE, prob = c(0.7, 0.3))
F[(B == "a") & (C == "d")] = sample(c("a", "b"), length(which((B == "a") & (C == "d"))), replace = TRUE, prob = c(0.9, 0.1))
F[(B == "b") & (C == "a")] = sample(c("a", "b"), length(which((B == "b") & (C == "a"))), replace = TRUE, prob = c(0.2, 0.8))
F[(B == "b") & (C == "b")] = sample(c("a", "b"), length(which((B == "b") & (C == "b"))), replace = TRUE, prob = c(0.3, 0.7))
F[(B == "b") & (C == "c")] = sample(c("a", "b"), length(which((B == "b") & (C == "c"))), replace = TRUE, prob = c(0.4, 0.6))
F[(B == "b") & (C == "d")] = sample(c("a", "b"), length(which((B == "b") & (C == "d"))), replace = TRUE, prob = c(0.4, 0.6))
F[(B == "c") & (C == "a")] = sample(c("a", "b"), length(which((B == "c") & (C == "a"))), replace = TRUE, prob = c(0.5, 0.5))
F[(B == "c") & (C == "b")] = sample(c("a", "b"), length(which((B == "c") & (C == "b"))), replace = TRUE, prob = c(0.5, 0.5))
F[(B == "c") & (C == "c")] = sample(c("a", "b"), length(which((B == "c") & (C == "c"))), replace = TRUE, prob = c(0.75, 0.25))
F[(B == "c") & (C == "d")] = sample(c("a", "b"), length(which((B == "c") & (C == "d"))), replace = TRUE, prob = c(0.75, 0.25))
G = numeric(5000)
G[(A == "a") & (F == "a")] = 3.75 + 2.25 * D[(A == "a") & (F == "a")] + 1.25 + E[(A == "a") & (F == "a")] + rnorm(length(which((A == "a") & (F == "a"))), sd = 0.05)
G[(A == "a") & (F == "b")] = 2.25 + 3.02 * D[(A == "a") & (F == "b")] + 1.05 + E[(A == "a") & (F == "b")] + rnorm(length(which((A == "a") & (F == "b"))), sd = 0.25)
G[(A == "b") & (F == "a")] = 1.50 + 4.07 * D[(A == "b") & (F == "a")] + 0.85 + E[(A == "b") & (F == "a")] + rnorm(length(which((A == "b") & (F == "a"))), sd = 0.15)
G[(A == "b") & (F == "b")] = 0.15 + 5.82 * D[(A == "b") & (F == "b")] + 1.85 + E[(A == "b") & (F == "b")] + rnorm(length(which((A == "b") & (F == "b"))), sd = 0.35)

a = data.frame(A = A, B = B, C = C, D = D, E = E, F = F, G = G, H = H)

